
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PRIVATE_POSTGRES_USER}     
      POSTGRES_PASSWORD: ${PRIVATE_POSTGRES_PASSWORD} 
      POSTGRES_DB: ${PRIVATE_POSTGRES_DB}          
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network: